# Generated by Django 4.1.4 on 2022-12-15 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
