# Generated by Django 4.1.4 on 2022-12-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop_helper.category', verbose_name='Категория продукта'),
        ),
        migrations.AlterField(
            model_name='recipesproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop_helper.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='recipesproducts',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='shop_helper.recipe', verbose_name='Рецепт'),
        ),
    ]
