# Generated by Django 4.1.4 on 2022-12-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_helper', '0009_recipe_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
