# Generated by Django 4.1.4 on 2022-12-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_helper', '0010_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
