# Generated by Django 4.1.4 on 2022-12-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_helper', '0012_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
